=== elsewhat/MovSimDroid/assets/config/multiModelTrafficSimulatorInput.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- ##################################################################### -->
<!-- DTD Validation Grammar for multi model traffic simulator              -->
<!-- (c) 2011,2012 Arne Kesting, Ralph Germ, Martin Budden, Martin Treiber -->
<!-- ##################################################################### -->


<!-- ############################################################################## -->
<!-- Short reference for xml dtd syntax -->
<!-- http://www.herongyang.com/XML/DTD-Syntax-of-DTD-Statements.html -->
<!-- http://www.mihaiu.name/2005/xml-dtd-reference/ -->
<!-- <!ELEMENT> this tag is used to define an XML element type name and its permissible sub-elements;  -->
<!-- <!ELEMEMT elementName EMPTY>  : this element cannot have content, but it can have attributes -->
<!-- Element can have children but it cannot contain text (with the exception of whitespace): -->
<!-- <!ELEMENT elementName (child1, child2)> : element's children are specified using a sequence list thus they must appear in the specified order -->
<!-- <!ELEMENT elementName (child1 | child2)> : element's children are specified using a mutually exclusive choice list -->
<!-- Cardinality operators: ?="0 or 1"; *="0 to n";+="1 to n" -->
<!-- <!ATTLIST>  defines the attributes of an XML element (permissible and default values) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #REQUIRED> : the attribute *must* be present in the XML document (is required) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #IMPLIED> : the attribute is optional -->
<!-- <!ATTLIST AnElement an_attribute CDATA "value"> : attribute is optional and it has a default value; a validating parser will supply the default value if the attribute is not specified in the respective element -->
<!-- <!ATTLIST Test6 an_attribute (value1 | value2) #IMPLIED> : the attribute is optional but it can only have values from a predefined list -->
<!-- ############################################################################## -->
<!-- Here NMTOKEN is used for "normal" values, (true|false) indicate defined boolean values and CDATA is used when parsing allows also for constructs like "1/3.6" -->
<!-- ############################################################################## -->


<!-- general remarks: -->
<!-- all parameter values are expected in SI units. Otherwise the attribute's name is indicating the unit explicitely -->

<!ELEMENT SCENARIO (FUEL_CONSUMPTION?, VEHICLES, SIMULATION) >

<!ATTLIST SCENARIO
  network_filename CDATA #REQUIRED
>


<!-- ##################################################################### -->
<!-- Fuel Consumption Model                                                -->
<!-- ##################################################################### -->

<!ELEMENT FUEL_CONSUMPTION (CONSUMPTION_MODEL+) >

<!ATTLIST FUEL_CONSUMPTION
>

<!ELEMENT CONSUMPTION_MODEL (CAR,ENGINE) >


<!ATTLIST CONSUMPTION_MODEL
  label   CDATA   #REQUIRED
  output  (true|false) "false" 
>

<!ELEMENT CAR EMPTY >
<!ATTLIST CAR
  mass                    NMTOKEN "1500"
  cross_section_surface   NMTOKEN "2.2"
  cd_value                NMTOKEN "0.32"
  electric_power          NMTOKEN "2000"
  const_friction          NMTOKEN "0.0145"
  v_friction              NMTOKEN "0"
  dynamic_tyre_radius     NMTOKEN "0.3113"
>

<!ELEMENT ENGINE (GEAR_RATIOS?) >
<!ATTLIST ENGINE
  max_power_kW  NMTOKEN "90"
  cylinder_vol_l  NMTOKEN "1.4"
  idle_cons_rate_linvh NMTOKEN "0.6"
  cspec_min_g_per_kwh NMTOKEN "212"
  pe_min_bar NMTOKEN "1"
  pe_max_bar NMTOKEN "19" 
  idle_rotation_rate_invmin NMTOKEN "1000"
  max_rotation_rate_invmin NMTOKEN "6000"
>

<!ELEMENT GEAR_RATIOS (GEAR_RATIO+) >
<!ATTLIST GEAR_RATIOS
>

<!ELEMENT GEAR_RATIO EMPTY >
<!ATTLIST GEAR_RATIO
  phi   NMTOKEN  #REQUIRED
>

     

<!-- ##################################################################### -->
<!-- Vehicle-Driver-Units / Models                                         -->
<!-- ##################################################################### -->

<!ELEMENT VEHICLES (VEHICLE+) >
<!ATTLIST VEHICLES
  write_fund_diagrams  (false|true) "false"
>


<!ELEMENT VEHICLE (LONGITUDINAL_MODEL, LANE_CHANGE_MODEL, NOISE?) >

<!ATTLIST VEHICLE
  label           CDATA   #REQUIRED
  length          NMTOKEN #REQUIRED
  width           NMTOKEN "4.4"
  b_max           NMTOKEN "10000"
  reaction_time   NMTOKEN "0"
  consumption     NMTOKEN "none"
>

<!-- Longitudinal model elements -->
<!ELEMENT LONGITUDINAL_MODEL (IDM?, ACC?, OVM_FVDM?, GIPPS?, KRAUSS?, NEWELL?, NSM?, KKW?, MEMORY?, CCS?)>

<!-- see IDM paper and/or website for reference -->
<!ELEMENT IDM EMPTY>
<!ATTLIST IDM 
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
>

<!ELEMENT ACC EMPTY>
<!ATTLIST ACC
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
  coolness     NMTOKEN #REQUIRED
>


<!-- default: OVM variant with org. optimal velocity function -->
<!ELEMENT OVM_FVDM EMPTY>
<!ATTLIST OVM_FVDM
  v0          NMTOKEN #REQUIRED
  tau         NMTOKEN #REQUIRED
  s0          NMTOKEN #REQUIRED
  l_int       NMTOKEN #REQUIRED
  beta        NMTOKEN #REQUIRED
  lambda      NMTOKEN "0"
  variant     (0|1|2) "0"
>


<!ELEMENT GIPPS EMPTY>
<!ATTLIST GIPPS
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
>

<!ELEMENT KRAUSS EMPTY>
<!ATTLIST KRAUSS
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  epsilon      NMTOKEN #REQUIRED
>

<!ELEMENT NEWELL EMPTY>
<!ATTLIST NEWELL
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
>

<!ELEMENT NSM EMPTY>
<!ATTLIST NSM
v0           NMTOKEN #REQUIRED
p_slowdown   NMTOKEN #REQUIRED
p_slow_start NMTOKEN #REQUIRED
>

<!ELEMENT KKW EMPTY>
<!ATTLIST KKW
v0      NMTOKEN #REQUIRED
k       NMTOKEN #REQUIRED
pb0     NMTOKEN #REQUIRED
pb1     NMTOKEN #REQUIRED
pa1     NMTOKEN #REQUIRED
pa2     NMTOKEN #REQUIRED
vp      NMTOKEN #REQUIRED
>

<!-- Memory model, see paper for reference -->
<!ELEMENT MEMORY EMPTY>
<!ATTLIST MEMORY
tau     NMTOKEN #REQUIRED
alpha_T  NMTOKEN #REQUIRED
alpha_v0 NMTOKEN #REQUIRED
alpha_a  NMTOKEN "1"
>

<!-- Cross coutry skiing model -->
<!ELEMENT CCS EMPTY>
<!ATTLIST CCS
  mass            NMTOKEN #REQUIRED
  cw              NMTOKEN #REQUIRED
  A               NMTOKEN #REQUIRED
  friction        NMTOKEN #REQUIRED
  p0              NMTOKEN #REQUIRED
  v_c             NMTOKEN #REQUIRED
  p_herringbone   NMTOKEN #REQUIRED
  v_c_herringbone NMTOKEN #REQUIRED
  T               NMTOKEN #REQUIRED
  s0              NMTOKEN #REQUIRED
  b               NMTOKEN #REQUIRED
  b_maximal       NMTOKEN #REQUIRED
>

<!ELEMENT LANE_CHANGE_MODEL (MOBIL?)>
<!ATTLIST LANE_CHANGE_MODEL 
eur_rules  (true|false) "false"
crit_speed_eur  NMTOKEN "25"
>


<!-- MOBIL as concrete lane-changing model -->
<!ELEMENT MOBIL EMPTY>
<!ATTLIST MOBIL 
b_safe          NMTOKEN "4.0"
s_min           NMTOKEN "2.0"
threshold       NMTOKEN "0.2"
bias_right      NMTOKEN "0.25"
politeness      NMTOKEN "0.1"
>

<!-- Fluctuations:  -->
<!-- Wiener process (tau!=0) or delta-correlated white noise as alternatives -->
<!-- default is white noise -->
<!-- too strong fluctuations can provoke crashed -->
<!ELEMENT NOISE EMPTY>
<!ATTLIST NOISE
tau              NMTOKEN "0"
fluct_strength   NMTOKEN #REQUIRED 
>


<!-- ##################################################################### -->
<!-- Infrastructure and Simulation settings                                -->
<!-- ##################################################################### -->

<!ELEMENT SIMULATION (TRAFFIC_COMPOSITION, ROAD*, ROUTES?, OUTPUT)>
<!ATTLIST SIMULATION
  dt               NMTOKEN #REQUIRED
  duration         NMTOKEN #REQUIRED
  fixed_seed       (true|false) "true" 
  seed             NMTOKEN "42"
  crash_exit       (true|false) "true"
> 



<!ELEMENT TRAFFIC_COMPOSITION (VEHICLE_TYPE+)>
<!ATTLIST TRAFFIC_COMPOSITION
>

<!ELEMENT VEHICLE_TYPE EMPTY >
<!ATTLIST VEHICLE_TYPE
  label     CDATA    #REQUIRED
  fraction  NMTOKEN  #REQUIRED
  relative_v0_randomization NMTOKEN "0.0"
  route_label CDATA ""
>



<!ELEMENT ROAD (TRAFFIC_COMPOSITION?, INITIAL_CONDITIONS?, TRAFFIC_SOURCE?, TRAFFIC_SINK?, FLOW_CONSERVING_INHOMOGENEITIES?, SPEED_LIMITS?, SLOPES?, SIMPLE_RAMP?, TRAFFIC_LIGHTS?, DETECTORS?)>

<!ATTLIST ROAD
  id               NMTOKEN #REQUIRED
  logging          (false|true) "false" 
> 


<!-- initial conditions (IC) -->
<!ELEMENT INITIAL_CONDITIONS (IC_MACRO*, IC_MICRO*)>
<!ATTLIST INITIAL_CONDITIONS 
> 

<!-- speed default value corresponds to equilibrium speed -->  
<!ELEMENT IC_MACRO EMPTY>
<!ATTLIST IC_MACRO
  x          NMTOKEN #REQUIRED
  rho_per_km NMTOKEN #REQUIRED
  v          NMTOKEN "-1"
> 

<!-- most right lane is =1, increment for further lanes  -->
<!ELEMENT IC_MICRO EMPTY>
<!ATTLIST IC_MICRO
  x       NMTOKEN #REQUIRED
  v       NMTOKEN #REQUIRED
  lane    NMTOKEN "1"
  label   CDATA ""
> 

<!-- upstream boundary conditions -->
<!ELEMENT TRAFFIC_SOURCE (INFLOW+)>
<!ATTLIST TRAFFIC_SOURCE
logging  (true|false)  "false" 
>          

<!-- downstream boundary conditions (not yet implemented) -->
<!ELEMENT TRAFFIC_SINK EMPTY>
<!ATTLIST TRAFFIC_SINK
logging  (true|false) "false" 
>          


<!ELEMENT INFLOW EMPTY>
<!ATTLIST INFLOW
  t           NMTOKEN #REQUIRED
  q_per_hour  NMTOKEN #REQUIRED
  v           NMTOKEN "20"
> 

<!-- Flow-conserving inhomogeneities -->
<!ELEMENT FLOW_CONSERVING_INHOMOGENEITIES (INHOMOGENEITY*)>
<!ATTLIST FLOW_CONSERVING_INHOMOGENEITIES
> 

<!ELEMENT INHOMOGENEITY EMPTY>
<!ATTLIST INHOMOGENEITY
x         NMTOKEN #REQUIRED
alpha_T   NMTOKEN "1"
alpha_v0  NMTOKEN "1"
> 

<!-- speed limits -->
<!ELEMENT SPEED_LIMITS (SPEED_LIMIT*)>
<!ATTLIST SPEED_LIMITS
>

<!ELEMENT SPEED_LIMIT EMPTY>
<!ATTLIST SPEED_LIMIT
x         NMTOKEN #REQUIRED
speedlimit_kmh NMTOKEN #REQUIRED
> 
<!-- slopes -->
<!ELEMENT SLOPES (SLOPE*)>
<!ATTLIST SLOPES
> 

<!ELEMENT SLOPE EMPTY>
<!ATTLIST SLOPE
x         NMTOKEN #REQUIRED
gradient  NMTOKEN #REQUIRED
> 

  
<!ELEMENT SIMPLE_RAMP (INFLOW*)>
<!ATTLIST SIMPLE_RAMP
logging  (true|false)  "false" 
> 
  
<!-- traffic lights -->
  
<!ELEMENT TRAFFIC_LIGHTS (TRAFFIC_LIGHT*)>
<!ATTLIST TRAFFIC_LIGHTS
  n_dt  NMTOKEN "1"
  logging  (true|false)  "false" 
>  

<!-- zero time period means that light will not change automatically from that color -->
<!-- negative time period means that light will not use that color -->
<!-- ordinal numbers of TrafficLightStatus are GREEN=0, GREEN_RED=1, RED=2, RED_GREEN=3 --> 
<!ELEMENT TRAFFIC_LIGHT EMPTY>
<!ATTLIST TRAFFIC_LIGHT
x                NMTOKEN #REQUIRED
green_time       NMTOKEN #REQUIRED
green_red_time   NMTOKEN #REQUIRED
red_time         NMTOKEN #REQUIRED
red_green_time   NMTOKEN #REQUIRED
phase_shift      NMTOKEN "0"
init             NMTOKEN "0"
> 


<!-- detectors can be placed with absolute and/or relative positions -->
<!ELEMENT DETECTORS  (CROSS_SECTION*) >
<!-- 1 min as default aggregation interval -->
<!ATTLIST DETECTORS
  dt  NMTOKEN "60" 
  logging  (true|false)  "false" 
>

<!ELEMENT CROSS_SECTION EMPTY>
<!ATTLIST CROSS_SECTION 
  x  NMTOKEN #REQUIRED 
>

<!ELEMENT ROUTES (ROUTE*)>
<!ATTLIST ROUTES
>

<!ELEMENT ROUTE (ROAD+)>
<!ATTLIST ROUTE
label  NMTOKEN #REQUIRED 
>


<!-- ##################################################################### -->
<!--                           OUTPUT                                      -->
<!-- ##################################################################### -->

<!ELEMENT OUTPUT (FLOATING_CAR_DATA?, SPATIOTEMPORAL*, TRAJECTORIES*, TRAVELTIMES*, FUEL*) >

<!ATTLIST OUTPUT
>

<!-- output of spatio-temporal fields -->
<!ELEMENT SPATIOTEMPORAL EMPTY>
<!ATTLIST SPATIOTEMPORAL
  dt NMTOKEN "60"
  dx NMTOKEN "100"
  route NMTOKEN #REQUIRED
>

<!-- possible output: dn and/or list  -->
<!ELEMENT FLOATING_CAR_DATA (FC*)>
<!ATTLIST FLOATING_CAR_DATA 
n_dt      NMTOKEN "1"
dn        NMTOKEN "0"
>

<!ELEMENT FC EMPTY>
<!ATTLIST FC
number  NMTOKEN #REQUIRED
>

<!-- example: <TRAJECTORIES dt_s="1" t_start_min="0" t_end_min="7" />  -->
<!ELEMENT TRAJECTORIES EMPTY>
<!ATTLIST TRAJECTORIES
  dt           NMTOKEN "1"
  start_time   NMTOKEN "0"
  end_time     NMTOKEN "1e10"
  route     NMTOKEN #REQUIRED
>


<!ELEMENT TRAVELTIMES EMPTY>
<!ATTLIST TRAVELTIMES
  route     NMTOKEN #REQUIRED
>

<!ELEMENT FUEL EMPTY>
<!ATTLIST FUEL
  dt           NMTOKEN "1"
  start_time   NMTOKEN "0"
  end_time     NMTOKEN "1e10"
  route     NMTOKEN #REQUIRED
>

=== elsewhat/MovSimDroid/assets/sim/games/two_in_two_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<!-- (c) Arne Kesting, Ralph Germ, Martin Budden, Martin Treiber (2012) -->
<SCENARIO network_filename="two_in_two_out.xodr">
    <FUEL_CONSUMPTION>
        <CONSUMPTION_MODEL label="carDiesel" type="fuel" output="false">
            <CAR mass="1500" cross_section_surface="2.2" cd_value="0.32" electric_power="3000" const_friction="0.015" v_friction="0" dynamic_tyre_radius="0.31" />
            <ENGINE max_power_kW="90" cylinder_vol_l="1.4" idle_cons_rate_linvh="0.8" cspec_min_g_per_kwh="185" pe_min_bar="1" pe_max_bar="22" idle_rotation_rate_invmin="900" max_rotation_rate_invmin="4500">
                <GEAR_RATIOS>
                    <GEAR_RATIO phi="16.7" />
                    <GEAR_RATIO phi="10.1" />
                    <GEAR_RATIO phi="6.8" />
                    <GEAR_RATIO phi="5.0" />
                    <GEAR_RATIO phi="3.8" />
                    <GEAR_RATIO phi="3.1" />
                    <GEAR_RATIO phi="2.6" />
                </GEAR_RATIOS>
            </ENGINE>
        </CONSUMPTION_MODEL>
    </FUEL_CONSUMPTION>
    <VEHICLES write_fund_diagrams="false">
        <VEHICLE label="ACC1" length="8.5" b_max="40" consumption="carDiesel" width="5.6" reaction_time="0">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0" coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="20.0" s_min="2.0" threshold="0.1" bias_right="0." politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <!-- trucks -->
        <VEHICLE label="ACC2" length="20" b_max="40" consumption="carDiesel" width="6.6" reaction_time="0">
            <LONGITUDINAL_MODEL>
                <ACC v0="25" T="1.4" s0="2" s1="2" delta="4" a="0.8" b="2.0" coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="20.0" s_min="2.0" threshold="0.2" bias_right="0.0" politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>        
        <VEHICLE label="Obstacle" length="0" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5" s1="0" delta="4" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.1" duration="86400" fixed_seed="true" seed="42" crash_exit="false">
        <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="ACC1" fraction="0.7" relative_v0_randomization="0.2" route_label="" />
            <VEHICLE_TYPE label="ACC2" fraction="0.3" relative_v0_randomization="0.2" route_label="" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="1" logging="false">
            <TRAFFIC_COMPOSITION>
                <VEHICLE_TYPE label="ACC1" fraction="0.7" relative_v0_randomization="0.2" route_label="" />
                <VEHICLE_TYPE label="ACC2" fraction="0.3" relative_v0_randomization="0.2" route_label="" />
            </TRAFFIC_COMPOSITION>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="0" v="20" />
                <INFLOW t="60" q_per_hour="1800" v="20" />
                <INFLOW t="120" q_per_hour="1800" v="20" />
                <INFLOW t="180" q_per_hour="0" v="20" />
            </TRAFFIC_SOURCE>
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.8" alpha_v0="1" />
                <INHOMOGENEITY x="200" alpha_T="1." alpha_v0="1" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <TRAFFIC_LIGHTS n_dt="1" logging="false">
                <!-- zero time period means that light will not change automatically from that color -->
                <!-- negative time period means that light will not use that color -->
                <!-- ordinal numbers of TrafficLightStatus are GREEN=0, GREEN_RED=1, RED=2, RED_GREEN=3 -->
                <TRAFFIC_LIGHT x="390" green_time="0" green_red_time="-1" red_time="0" red_green_time="-1" phase_shift="0" init="0" />
            </TRAFFIC_LIGHTS>
        </ROAD>
        
         <ROAD id="10" logging="false">
            <TRAFFIC_COMPOSITION>
                <VEHICLE_TYPE label="ACC1" fraction="0.5" relative_v0_randomization="0.2" route_label="" />
                <VEHICLE_TYPE label="ACC2" fraction="0.5" relative_v0_randomization="0.2" route_label="" />
            </TRAFFIC_COMPOSITION>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="0" v="20" />
                <INFLOW t="20" q_per_hour="1200" v="20" />
                <INFLOW t="120" q_per_hour="500" v="20" />
                <INFLOW t="150" q_per_hour="100" v="20" />
                <INFLOW t="180" q_per_hour="0" v="20" />
                
            </TRAFFIC_SOURCE>
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.8" alpha_v0="1" />
                <INHOMOGENEITY x="200" alpha_T="1." alpha_v0="1" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <TRAFFIC_LIGHTS n_dt="1" logging="false">
                <!-- zero time period means that light will not change automatically from that color -->
                <!-- negative time period means that light will not use that color -->
                <!-- ordinal numbers of TrafficLightStatus are GREEN=0, GREEN_RED=1, RED=2, RED_GREEN=3 -->
                <TRAFFIC_LIGHT x="385" green_time="0" green_red_time="-1" red_time="0" red_green_time="-1" phase_shift="0" init="2" />
            </TRAFFIC_LIGHTS>
        </ROAD>
        

        
        <OUTPUT />
    </SIMULATION>
</SCENARIO>

=== elsewhat/MovSimDroid/assets/sim/buildingBlocks/ringroad_1lane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<!-- (c) Arne Kesting, Ralph Germ, Martin Budden, Martin Treiber (2012) -->
<!-- TODO: FCD Output does not work with macroscopic initial conditions -->
<SCENARIO network_filename="ringroad.xodr">
  <VEHICLES write_fund_diagrams="false">
    <VEHICLE label="IDM" length="8" b_max="9" width="5.4" reaction_time="0" consumption="none">
      <LONGITUDINAL_MODEL>
        <IDM v0="30" T="1.2" s0="2" s1="0" delta="4" a="0.5" b="2.0" />
      </LONGITUDINAL_MODEL>
      <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
      <!-- fluctuation strength needed for traffic flow breakdown if simulating only with one vehicle type -->
      <NOISE tau="5" fluct_strength="0.07" />
    </VEHICLE>
  </VEHICLES>
  <SIMULATION dt="0.07" duration="100000" fixed_seed="true" seed="42" crash_exit="true">
    <TRAFFIC_COMPOSITION>
      <VEHICLE_TYPE label="IDM" fraction="1" relative_v0_randomization="0.0" route_label="" />
    </TRAFFIC_COMPOSITION>
    <ROAD id="1" logging="false">
      <INITIAL_CONDITIONS>
        <!-- critical density for emerging stop-and-go wave about >= 33 vehicles per km per lane -->
        <IC_MACRO x="1" rho_per_km="36" v="20" />
      </INITIAL_CONDITIONS>
    </ROAD>
    <OUTPUT>
      <FLOATING_CAR_DATA n_dt="5" dn="0">
        <FC number="2" />
      </FLOATING_CAR_DATA>
    </OUTPUT>
  </SIMULATION>
</SCENARIO>

=== elsewhat/MovSimDroid/assets/sim/bookScenarioStartStop/startStop_all_ca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<!-- (c) Movsim, Arne Kesting 2012 -->
<SCENARIO network_filename="startStop_all_ca.xodr">
    <VEHICLES write_fund_diagrams="false">
        <!-- vehicle length ==> cell units -->
        <VEHICLE label="NSM1" length="1" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <NSM v0="2" p_slowdown="0.1" p_slow_start="0.1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
        <VEHICLE label="BARL1" length="1" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <NSM v0="2" p_slowdown="0.1" p_slow_start="0.2" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
        <VEHICLE label="KKW1" length="20" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <KKW v0="28" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="14" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
        <VEHICLE label="ObstacleNSM" length="1" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <NSM v0="0" p_slowdown="0" p_slow_start="0" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
        <VEHICLE label="ObstacleKKW" length="20" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <KKW v0="0" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="14" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="1" duration="150" fixed_seed="true" seed="42" crash_exit="false">
        <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="NSM1" fraction="1" relative_v0_randomization="0.0" route_label="" />
            <VEHICLE_TYPE label="BARL1" fraction="1" relative_v0_randomization="0.0" route_label="" />
            <VEHICLE_TYPE label="KKW1" fraction="1" relative_v0_randomization="0.0" route_label="" />
            <!-- KKW and NSM not compatible. Obstacle works only for same model -->
            <VEHICLE_TYPE label="ObstacleNSM" fraction="0" relative_v0_randomization="0.0" route_label="" />
            <VEHICLE_TYPE label="ObstacleKKW" fraction="0" relative_v0_randomization="0.0" route_label="" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="Nagel Schreckenberg Model. Cell length: 7.5 m" logging="false">
            <INITIAL_CONDITIONS>
                <!-- in physical quantities (meter and m/s) -->
                <IC_MICRO x="7.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="15.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="22.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="30.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="37.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="45.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="52.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="60.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="67.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="75.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="82.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="90.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="97.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="105.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="112.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="120.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="127.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="135.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="142.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="150.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="157.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="165.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="172.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="180.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="187.5" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="195.0" v="0" label="NSM1" lane="1" />
                <IC_MICRO x="1000" v="0" label="ObstacleNSM" lane="1" />
            </INITIAL_CONDITIONS>
        </ROAD>
        <ROAD id="Barlovic Model. Cell length: 7.5m" logging="false">
            <INITIAL_CONDITIONS>
                <!-- in physical quantities (meter and m/s) -->
                <IC_MICRO x="7.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="15.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="22.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="30.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="37.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="45.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="52.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="60.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="67.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="75.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="82.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="90.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="97.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="105.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="112.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="120.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="127.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="135.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="142.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="150.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="157.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="165.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="172.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="180.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="187.5" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="195.0" v="0" label="BARL1" lane="1" />
                <IC_MICRO x="1000" v="0" label="ObstacleNSM" lane="1" />
            </INITIAL_CONDITIONS>
        </ROAD>
        <ROAD id="Kerner Klenov Wolf Model. Cell length: 0.5m" logging="false">
            <INITIAL_CONDITIONS>
                <!-- in physical quantities (meter and m/s) -->
                <IC_MICRO x="10" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="20" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="30" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="40" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="50" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="60" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="70" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="80" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="90" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="100" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="110" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="120" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="130" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="140" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="150" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="160" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="170" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="180" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="190" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="200" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="210" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="220" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="230" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="240" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="250" v="0" label="KKW1" lane="1" />
                <IC_MICRO x="1000" v="0" label="ObstacleKKW" lane="1" />
            </INITIAL_CONDITIONS>
        </ROAD>
        <OUTPUT />
    </SIMULATION>
</SCENARIO>
